### PR TITLE
Replace if condition with literal if possible to simplify if statement

### PR DESCRIPTION
**Pull request by viirya**
This is my first time to contribute codes to janino. Please let me know if it is ok for you. Thank you.

This is an optimization for if statement. It tried to optimize the following case:

    boolean test = true;
    if (test) {
      ...  // then block
    } else {
      ...  // else block
    }

In this case, we can replace the condition as the literal `true`, so in compilation it will be further optimized to only the then block.

It can be argued that it might be rare to see hand-written codes like that. However, if we generate java codes programmatically, it is not rare to see generated codes like that.

If we could automatically replace the condition with the literal, we can reduce if statement and corresponding bytecodes.

### CODE REVIEW

**Comment by aunkrig** [comment]
Hello Hsieh,

first of all, thank you for your contribution. I agree this this optimization does make sense. JANINO (to my knowledge) is often used in systems that generate code, so you're definitely not alone with this topic.

However, although it may be the easiest way in this case, this optimization should not be imlemented _in the parser_, because parsing and unparsing should definitely be biunique. Two reasons for this that come to my mind are:

- The parser is not only used for compiling, but also in other contexts
- The possibilities for optimization are very limited

If you want a "quick fix" for only a special case, then I would recommend that you pre-process the source code with regular expressions. While this may seem awkward at first glance, it moves the optimization closer to the origin of the problem, and also separates the optimization very well from the code generator and from JANINO.

I will check if I can implement the optimization in the JANINO **compiler** and get to a solution that is useful for many users.

**Comment by viirya** [comment]
@aunkrig Thanks for replying this and the suggestion.

I have first wanted to implement this in compiler too. However, the first attempt is not successful. Then I turn to have this is parser. Your concern is very correct.

I will close this now and continue to look into implementing this in compiler.

**Comment by aunkrig** [comment]
Hello Hsieh,

I just implemented the optimization in the compiler on the MASTER branch; please test.

**Comment by viirya** [comment]
@aunkrig Thanks, that's cool! I am looking at it.

**Comment by viirya** [comment]
@aunkrig Thanks for your implementation! That's looks good to me and is exactly what I want.

I made a little change to it to allow interweaving other local variable declarations. May you take a look if it is ok for you? Thank you.

**Comment by aunkrig** [comment]
Hi there,

I understand what you intend, but am afraid that I cannot merge the code, because the optimization would not generate incorrect code in some circumstances.
The reason being is that the variable  declarators' initializer expressions could modify the value of "our" variable, so the optimization is only permissible for the LAST declarator.

But I'll look into it again. Stay tuned!

**Comment by viirya** [comment]
@aunkrig Thanks for pointing it out. I'll try to dig into this too. Thank you.

**Comment by viirya** [comment]
Hi @aunkrig 

For the possibility that the initializer could change the value of "our" variable, I added the check.

If the initializer is a non-constant Rvalue, we won't do the optimization

E.g.,

        boolean test = true;
        boolean test2 = (test = false);
        if (test) {
          ...
        } else {
          ...
        }

or

        boolean test = true;
        boolean test2 = test;
        if (test) {
          ...
        } else {
          ...
        }

This takes a more conservative approach. But it should be safer. What do you think?

**Comment by kiszk** [comment]
Is there any update on this? As @aunkrig pointed out, this is good for the generated code.

**Comment by viirya** [comment]
ping @aunkrig, I have update on this. Can you take a look and let me know if it is proper? Thanks.

**Comment by kiszk** [comment]
ping @aunkrig

**Comment by kiszk** [comment]
@aunkrig would it be possible to review this?

**Comment by kiszk** [comment]
@aunkrig we would appreciate it if you give us your thoughts about this.

**Comment by kiszk** [comment]
@aunkrig would it be possible to review this?

**Comment by aunkrig** [comment]
Sorry for the late response... I eventually merged (and further improved) your proposed fix, and added your (and more) unit tests.

Please test, and re-open this PR if you find any issues.

**Pull request closed without merging**
