### PR TITLE
Reuse local variable slots among non-overlapping scopes

### PR DESCRIPTION
**Pull request by rednaxelafx**
Reuse local variable slots among non-overlapping scopes, i.e. pop the slots used in a scope when going out of the scope.

### CODE REVIEW

**Comment by aunkrig** [comment]
Brilliant work! Merged.

**Comment by rednaxelafx** [comment]
Thank you very much, @aunkrig ! Wish you a Happy New Year!

**Comment by rednaxelafx** [comment]
Ahh...It looks like the PR was closed but the commit didn't go into master branch, though.

**Comment by aunkrig** [comment]
I merged it manually and committed it to the MASTER branch.

**Comment by aunkrig** [comment]
You're right... I forgot to commit the changes. Now it's done -- please review!

**Comment by rednaxelafx** [comment]
LGTM, thanks @aunkrig !

**Comment by richard-steiger** [comment]
_(This is a copy of issue #8 I just filed, want to make sure one of you sees it, since this is blocking an urgent project.  If there's a stable branch, please let me know.  Thanks much in advance.)_

I just cloned the master branch of all projects, and did a "mvn install" in the janino-parent, got the above error message. Eclipse reports 12 compilation errors in CodeContext, at least some of them are in new lines added in the last commit.
A (related?) mystery: the directories under src on down are marked "-tmp-", suggesting that these changes are WIP (Work in Process).
Please advise.
Thanks for building this suite! When I can get a working version, it'll save me many weeks replicating the core functionality.

**Comment by aunkrig** [comment]
@richard-steiger That commit was a mistake of mine; it's now fixed.

**Comment by richard-steiger** [comment]
Hate to be the bearer of poor news, but my attempt to use Janino on my project fell apart: the subject code is at JLS8, and the parser bombs when encountering method references.  If/when extended to JLS8, please let me know.
Thanks again,
-rjs

**Comment by aunkrig** [comment]
Sorry for that... please notice that all supported and not-supported language features are documented on the home page.

**Comment by richard-steiger** [comment]
Yes, the feature set was very clearly set-out on the home page, and I'd 
overlooked them, so all blame goes to me, or as the saying goes, RYFM 
8-). Meanwhile, I'm going to use Antlr.

-rjs

**Comment by aunkrig** [comment]
Does that mean you're using Janino for code analysis/manipulation and not for compilation?

**Comment by richard-steiger** [comment]
The current project focus is static analysis and refactoring plan 
generation.  I need (and was hoping for) a quick win.

A second project (that's been on-again-off-again for the last decade++) 
is development of a new language suite that will run initially on the 
JVM, but over time will include native code generation.  Very innovative 
(and have been told "insanely ambitious" by many colleagues), and at 
this point, I'm starting to look seriously at Janino, a heavily 
refactored Antlr4 variant, and Graal + Truffle.  None of these are 
silver bullets, but each provides a lot of valuable functionality.  FYI, 
I haven't decided whether this will be totally open-source, or based on 
some fremium model, or just outright proprietary product (there are 
extremely strong arguments in favor of each, and I'm trying to quit day 
jobs, so getting a cash-stream from it is a critical aspect of the project).

I'm curious why you chose to hand-code the compiler, as opposed to at 
least generating lexer and parser using any of the parser-generators 
lying around.  The code is very nice and readable, and it looks pretty 
maintainable.  I also don't see JLS evolving much going forward, so your 
decision wasn't a risky one.   I was even contemplating adding 
recognition code to Janino for method references and whatever other JLS8 
functionality my project tripped-over, but I haven't been able to argue 
myself out of the near certainty that starting down that slope won't get 
precipitous, with no sane bottom.  (I have a day job out of necessity, 
sigh.)

Another question: care to hazard a guess as to how many software 
engineering-years Janino has absorbed to date?

Last question (for now): what's your vision for the project, what 
direction do you think is most likely and/or contributes the most?

Thanks for taking the time to discuss this corner of software 
engineering, something in which none of my current colleagues can engage 
(nor are very interested).

Cheers,

-rjs

**Comment by aunkrig** [comment]
Method references are now parsed (but compilation issues an NYI error), see #77. Is that helpful for you?

**Comment by aunkrig** [comment]
Same for "type inference syntax" (issue #78).

**Pull request closed without merging**
