### PR TITLE
StackOverflowError when using field annotations with enum members.

### PR DESCRIPTION
**Pull request by krullert**
Added a testcase (testBugAnnotationsStackOverflowError) to ReportedBugsTest for reproduction.

### CODE REVIEW

**Comment by krullert** [comment]
Ive added the fix in UnitCompiler, problem was a infinite recursion due to an eager toIAnnotations call.

**Comment by krullert** [comment]
apparently the StackOverflowError also happened on other locations (methods and constructors), added the extra fixes to the pull request.

**Comment by oontvoo** [comment]
Hi, I'm not following why we need these  "RuntimeRetainedAnnotationX" classes

**Comment by krullert** [comment]
Hi @oontvoo, They are for the various testcases in the ReportedBugsTest class, there was another bug when using String values instead of enums for runtime annotations, and another bug when using direct string constants without context identifier.

**Comment by aunkrig** [comment]
Merged the test case. Was able to reproduce the problem.

**Comment by aunkrig** [comment]
I just merged your pull request... thank you for your support.
Please review my changes, because I modified yours a bit, and not all of your changes are backed by your test case.

**Comment by aunkrig** [comment]
Closed due to lack of responses.

**Pull request closed without merging**
